export {default as Home} from './Home'
export {default as Product} from './Product'
export {default as Catalog} from './Catalog'
export {default as Profile} from './Profile'
export {default as About} from './About'
export {default as Cart} from './Cart'